language: node_js
before_script:
    - npm install -g karma-cli jasmine karma karma-jasmine karma-phantomjs-launcher karma-chrome-launcher karma-firefox-launcher karma-sauce-launcher
node_js:
  - '4'
  - '0.12'
  - '0.10'
